tests/test_vectors.nim
PR https://github.com/nim-lang/Nim/pull/11107 in `nim-lang/Nim` introduces new procs `fromHex` that conflicts with the `nimcrypto.fromHex` used in the `test_vectors.nim`.
To fix it, `fromHex` should not be imported from `strutils`.
=> Fix nimcrypto/utils.fromHex conflict with the new strutils.fromHex

blscurve/common.nim, blscurve/milagro.nim
c/nim must match/be correct when linking wasm
=> fix fshr function signature

blscurve.nimble, blscurve/common.nim, blscurve/hash_to_curve.md, blscurve/hash_to_curve.nim, blscurve/hkdf.nim, blscurve/milagro.nim, tests/all_tests.nim, tests/ietf_hash_to_curve.nim, tests/test_scheme.nim, tests/test_vectors.nim
This a WIP implementing the new hashToG2 primitive according to the IETF draft spec.
- IETF Standard Draft: https://tools.ietf.org/html/draft-irtf-cfrg-hash-to-curve-04
- Formatted HTML version: https://cfrg.github.io/draft-irtf-cfrg-hash-to-curve/draft-irtf-cfrg-hash-to-curve.html
- IETF Implementation: https://github.com/cfrg/draft-irtf-cfrg-hash-to-curve
- The following can be used as a test vector generator:
https://github.com/cfrg/draft-irtf-cfrg-hash-to-curve/blob/6cf7fa97/poc/suite_bls12381g2.sage
- Ethereum Foundation implementation: https://github.com/ethereum/py_ecc
- Specific PR: https://github.com/ethereum/py_ecc/pull/83/files
Currently, the implementation is incorrect and need heavy debugging. Unfortunately I'm lacking some test vectors. Py-ECC code doesn't follow the spec …
=> IETF hash to g2

blscurve/bls_signature_scheme.nim, blscurve/hash_to_curve.nim, blscurve/hkdf.nim
This PR changes 2 things:
1. it uses a DBIG_384 (double BIG_384) in to hold the raw bytes coming from HKDF-expand.
Some of the raw outputs require more than 381-bit
With a BIG the fromBytes procedure doesn't fail, the resulting BIG can be printed but calling norm or mod on it gives incorrect result and this creates an invalid secret key that causes stack smashing issues: https://github.com/status-im/nim-blscurve/issues/40#issuecomment-597573079, https://github.com/status-im/nim-beacon-chain/pull/780
2. In the process of debugging, I changed HKDF to use openarray thinking that the rootcause was hidden in some raw pointers
=> Fix secretKey bigger than curve order and stack smashing in ECP mul

blscurve/bls_signature_scheme.nim
HKDF has an openarray API instead of pointer+length so the salt message can be a const string
=> Use const salt

README.md, tests/eth2_vectors.nim, tests/fuzzing/collect_corpus.nim, tests/fuzzing/fuzz_verify.nim, tests/fuzzing/fuzzing_assumptions.nim, tests/fuzzing/run_fuzzing_test.nims, tests/test_locator.nim
To try this, fetch the latest version of `nim-testutils` and follow the instructions in the READMEs.
=> Add an example fuzzing test

blscurve/bls_signature_scheme.nim
Ready to commit. But 32-bit Windows Azure shows:
```
========================== Starting Command Output ===========================
"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/4646d1d4-3400-4b89-a5ae-90c117ab9ce9.sh
PATH=/mingw64/bin:/usr/bin:/c/Users/VssAdministrator/bin:/c/agents/2.170.1/externals/git/cmd:/c/Program Files/Mercurial:/c/Program Files/MongoDB/Server/4.2/bin:/c/ProgramData/kind:/c/Program Files/PostgreSQL/12/bin:/c/vcpkg:/c/cf-cli:/c/Program Files (x86)/NSIS:/c/Program Files/Mercurial:/c/hostedtoolcache/windows/stack/2.3.1/x64:/c/ProgramData/chocolatey/lib/ghc.8.10.1/tools/ghc-8.10.1/bin:/c/Program Files/dotnet:/c/mysql-5.7.21-winx64/bin:/c/Program Files/Java/zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64/bin:/c/SeleniumWebDrivers/GeckoDriver:/c/Program …
```
=> Switch default to BLS draft v7, used by v0.12.x

.gitignore, blscurve.nimble, blscurve/blst/bls_sig_min_pubkey_size_pop.nim, blscurve/blst/blst_lowlevel.nim, tests/priv_to_pub.nim, tests/priv_to_pub.sage
This fixes a bug that appeared when updating nim-blscurve in the NBC repo https://github.com/status-im/nim-beacon-chain/pull/1491
NBC is automatically compiled in release mode, which uses `-O3` underneath.
BLST is incompatible with some `-O3` flags that must be deactivated with `-fno-tree-loop-vectorize`
The test suite now tests in release mode as well and has been expanded with `privToPub` vectors
Raised upstream: https://github.com/supranational/blst/issues/22
=> Priv to pub blst

blscurve/bls_backend.nim
See https://github.com/status-im/nim-beacon-chain/issues/1555
=> check if SSSE3 is supported before enabling BLST by default on AMD64

.github/workflows/ci.yml, .travis.yml, README.md, blscurve.nimble
We need tests on 32-bit platforms to ensure the Miracl fallback is working fine.
Unfortunately we have 2 issues with the Azure CI right now.
1. Azure has OpenSSL issues, which are hopefully addressed by https://github.com/status-im/nim-blscurve/pull/82
2. Azure wait times are very long 
This also adds PowerPC (Little Endian only) to Travis CI
=> Github Actions CI + Travis PowerPC

blscurve/blst/bls_sig_min_pubkey_size_pop.nim, blscurve/blst/blst_abi.nim
This bumps BLST to the latest master.
Since BLSv4 commit which is the current one nimbus ETH2 builds with we have the following improvements:
(https://github.com/status-im/nim-blscurve/compare/3878b9b...master)
- Group checks can now be done at deserialization only and are now optional at BLS verification time.
This is how we use Milagro already and we paid unnecessary group checks with BLST until now.
With fast subgroup checks the cost of those checks isn't that high,1/4 to 1/2 of a scalar multiplication https://github.com/status-im/nim-blst/issues/1, https://github.com/mratsim/constantine/issues/47, which is significantly less costly than pairing but when a block is filled with 128 attestations it's still significant. Probable perf improvement 8~18% (maybe more?). …
=> Bump BLST - backend perf improvements

blscurve.nim, blscurve.nimble, blscurve/bls_backend.nim
The new BLST has a no-assembly fallback for non-ARM64 non-AMD64 targets.
Hence we can no use BLST instead of Miracl/Milagro throughough.
=> Use the new BLST no assembly fallback on 32-bit

blscurve/blst/bls_sig_min_pubkey_size_pop.nim, blscurve/blst/blst_abi.nim
This uses the new primitives mentioned in #92 for cached group checks.
Now we check at deserialization:
- if a pubkey is infinity or not in the subgroup
- if a signature is not in the subgroup (we may deserialize empty signatures)
Instead of checking that at verification time. Since public keys are reused multiple time this is a significant performance improvement.
New perf
In #97 we had
So we cumulated a total of (4025212-4588537)/(4588537) = 12.2% perf improvement compared to the current BLST in Nimbus.
Closes #42 as well
=> Cached group checks

.travis.yml, blscurve.nimble, blscurve/bls_backend.nim
This tests the suggested patch https://github.com/supranational/blst/issues/46#issuecomment-738939501
for a no assembly fallback.
In https://github.com/status-im/nim-blscurve/pull/96 we could use BLS on non x86 and non ARM 64-bit target as the #if #elif branch where missing that case.
The relevant test to check is Travis PowerPC 64.
~~This uses a patch that isn't upstream in travis.yml~~
The patch has been successfully tested and integrated in the master branch of BLST.
So this PR bumps BLST and uses it on non-x86, non-ARM. THis seems to work on Travis on PowerPC64.
This means that there is no reason to continue maintaining the Miracl backend, especially once BLST completes their security audit and formal verification. Unless we want a fallback for things like …
=> BLST no ASM flag for non-x86 non-ARM

benchmarks/bench_all.nim, benchmarks/bench_sha256.nim, benchmarks/bench_templates.nim, benchmarks/bls_signature.nim, blscurve.nimble, blscurve/bls_batch_verifier.nim, blscurve/bls_public_exports.nim, blscurve/bls_sig_min_pubkey.nim, blscurve/blst/blst_min_pubkey_sig_core.nim, blscurve/blst/sha256_abi.nim, blscurve/eth2_keygen/hkdf_mod_r_blst.nim, blscurve/openmp.nim, tests/t_batch_verifier.nim
This adds batched multi-signature verification to the library.
Both with serial or parallel backend with OpenMP.
The algorithm chosen is recursive divide-and-conquer instead of the usual parallel for loop,
this makes it easily portable to any threadpool that supports task spawning.
Unfortunately it is very easy to get confused with BLS signatures, signature aggregation and multi signature.
We have a triplet (pubkey, message, signature) to verify.
This is the base case `verify` https://github.com/status-im/nim-blscurve/blob/b0a1d149e97142649bd99c4acebcf551b7b05dda/blscurve/bls_sig_min_pubkey.nim#L108-L114
We have N public keys verifying the same message (attesting for a block for example)
This is `fastAggregateVerify`. https://github.com/status-im/nim-blscurve/blob/b0a1d149e97142649bd99c4ac …
=> Parallel and Serial batch verification

blscurve.nimble
When nimble is used to add blscurve to a nim project, the following error appears:
```
gcc: error: ../../vendor/blst/build/assembly.S: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: ../../vendor/blst/src/server.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
```
This PR adds the 'vendor' directory to the list of directories that should be installed, fixing the issue.
=> Fix compilation error because of missing vendor directory

blscurve/blst/blst_min_pubkey_sig_core.nim, blscurve/miracl/bls_sig_io.nim, blscurve/miracl/miracl_min_pubkey_sig_core.nim, docs/bls_types_guarantees.md, tests/priv_to_pub.nim
This fixes #114 and https://github.com/status-im/nimbus-eth2/issues/2695
In BLSCurve, preconditions checks for:
- SecretKey: 0 < SK < r (BLS12-381 curve order)
- PublicKey: PK != infinity and PK in G1 subgroup
are done at deserialization time.
https://github.com/status-im/nim-blscurve/blob/50dbaba38fbe451cf8620e433fe0fdffe2c215f0/blscurve/blst/bls_sig_io.nim#L149-L168
https://github.com/status-im/nim-blscurve/blob/50dbaba38fbe451cf8620e433fe0fdffe2c215f0/blscurve/blst/bls_sig_io.nim#L81-L99
This means that procedures that rely on those types, like `publicFromSecret` can assume that those preconditions are already respected.
This has been clarified in a dedicated document https://github.com/status-im/nim-blscurve/blob/9b7366cdc7df14c87930c3ed0243ab551a5daf56/docs/bls_types_guarantees.md …
=> SecretKey -> PublicKey preconditions docs + fixes.

tests/serialization.nim
Apparently we have CookedSig issues in Altair sending 0x0000...0000 instead of 0xc000...0000.
This ensures that the issue is not within blscurve
=> Add test for default init sig

blscurve/bls_sig_min_pubkey.nim, tests/eth2_vectors.nim
In #100 a regression was introduced to BLST `fastAggregateVerify`.
Previous code:
```
var aggAffine{.noInit.}: PublicKey
aggAffine.point.blst_p1_to_affine(aggregate)
return coreVerifyNoGroupCheck(aggAffine, message, signature, DST)
```
New code introducing regression:
```
var aggAffine{.noInit.}: PublicKey
aggAffine.finish(aggAffine)
return coreVerifyNoGroupCheck(aggAffine, message, signature, DST)
```
This change led to a compilation error when using `fastAggregateVerify`
with proof-of-possession.
Secondly, `aggregateVerify` with proof-possession also fails to compile.
This was never working, ever since BLST support was introduced in #68.
Problematic code:
```
if publicKeys.len != proofs.len or publicKeys != messages.len:
return false
```
This patch addresses both compilation problems …
=> Fix BLST aggregate verify with proof-of-possession

README.md, benchmarks/bls_signature.nim, blscurve/bls_backend.nim, blscurve/blst/blst_lowlevel.nim, blscurve/blst/blst_min_pubkey_sig_core.nim
Also fix some CI benchmarks and no longer pass "-fno-tree-vectorize" to the C compiler.
=> BLST: allow disabling SSSE3 support

blscurve/miracl/bls_sig_io.nim, tests/serialization.nim
1. Harden against seemingly valid BLS signature. https://github.com/status-im/nimbus-eth2/issues/555 For a while the Milagro/Miracl backend accepted an infinity point as long as it has the infinity bit flag set, it didn't require the rest of the bits to be all zeros. The BLST backend wasn't affected. This was fixed in #121 (along with #64 and #74). The corresponding EF test is `deserialization_fails_infinity_with_true_b_flag.json` This PR merely adds https://github.com/status-im/nimbus-eth2/issues/555 as a dedicated test case
=> Close remaining sec issues

benchmarks/bls12381_curve.nim, blscurve/bls_public_exports.nim, blscurve/miracl/common.nim
- The old hashToG2 was from June 2019, for Ethereum 2 development phase and has been superceded by the IETF draft standard
- Remove unused procs
=> Remove old hashToG2 and unused implementations #78

blscurve.nimble, blscurve/bls_backend.nim
So it turns out that `staticExec` (alias `gorge/gorgeEx`) behaves strangely on Windows. Not only is "/dev/null" not available in a Mingw-w64 environment, but pipes don't work inside the command. Not even when using `bash -c 'foo | bar'` explicitly.
=> fix SSSE3 detection on Windows

blscurve/eth2_keygen/blst_vect.nim, blscurve/eth2_keygen/hkdf_mod_r_blst.nim
Without this fix, compilations of dependent projects might fail depending on the specific library functions being used. See the failing CI runs of https://github.com/status-im/nimbus-eth2/pull/3616/commits/ced861e2c9656c92171ae452aa9acbf09b99b265 as an example.
=> Work-around https://github.com/supranational/blst/issues/29

blscurve/blst/blst_sha256.c, blscurve/blst/sha256_abi.nim
Instead of exporting Nim functions that call the C header functions,
create a tiny C module that does the same thing - this simplifies
getting the #include's right and works with `nlvm`
* fix context object definition
* fix raises and function declarations
=> simplify C export

benchmarks/bls_signature.nim, blscurve/bls_batch_verifier.nim, tests/eth2_vectors.nim, tests/t_batch_verifier.nim
The current version of `batchVerifyParallel` calls `syncAll` which syncs on all executing tasks.
This PR changes this to syncing a Flowvar instead thus allowing `batchVerifyParallel` to be called as a task itself.
Requires https://github.com/status-im/nim-taskpools/pull/33
=> avoid blocking batchVerifyParallel

blscurve.nimble, blscurve/bls_batch_verifier.nim
In Nim 2.0, `bls_batch_verifier` seems to need `{.push: raises: [].}`.
```
/home/runner/work/nimbus-eth2/nimbus-eth2/nimcache/release/resttest/@m..@svendor@snim-bearssl@sbearssl@scsources@ssrc@scodec@senc16be.c.o /home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-bearssl/bearssl/abi/../csources/src/codec/enc16be.c
/home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-blscurve/blscurve/bls_batch_verifier.nim(246, 22) template/generic instantiation of `spawn` from here
/home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-taskpools/taskpools/taskpools.nim(503, 70) template/generic instantiation of `toTask` from here
/home/runner/work/nimbus-eth2/nimbus-eth2/vendor/nim-taskpools/taskpools/tasks.nim(216, 65) template/generic instantiation from here …
```
=> add `{.push: raises: [].}` annotation

README.md, milagro.nims
Folders in README.md are no longer accurate. Bump to current structure.
=> update instructions for tracking upstream MIRACL Core

README.md, miracl.nims
Followup from #66 where we switched from Milagro to MIRACL Core. The script to prepare C sources was not yet renamed. Doing now.
=> rename `milagro.nims` -> `miracl.nims`

blscurve/miracl/miracl.nim
Followup from #66 where we switched from Milagro to MIRACL Core. The internal constants / pragma for importing / exporting were not yet renamed. Doing now.
=> rename `milagro(Path|_func)` -> `miracl(Path|_func)`

benchmarks/bls12381_curve.nim, benchmarks/platforms/x86.nim, blscurve/bls_batch_verifier.nim, blscurve/eth2_keygen/eth2_keygen.nim, blscurve/miracl/common.nim, blscurve/miracl/hash_to_curve.nim, blscurve/miracl/miracl.nim
Followup from #66 where we switched from Milagro to MIRACL Core. The internal documentation was not fully updated for Miracl. Doing now.
=> rename `milagro` references -> `miracl` in documentation

README.md
`nim-beacon-chain` was renamed to `nimbus-eth2`, update references.
=> Update `nimbus-eth2` reference

blscurve/blst/blst_abi.nim, blscurve/blst/blst_min_pubkey_sig_core.nim, tests/t_batch_verifier.nim
Use latest `csources` to regenerate `blst_abi.nim` and re-apply manual customization steps to minimize diff.
=> Regenerate `blst_abi.nim`

benchmarks/bench_all.nim, benchmarks/bls_signature.nim, blscurve/bls_batch_verifier.nim, blscurve/blst/blst+nim.h, blscurve/blst/blst_abi.nim, blscurve/blst/blst_min_pubkey_sig_core.nim, tests/t_batch_verifier.nim
In many use cases, there are multiple signatures of the same message, e.g., Ethereum attestations often share the signed `AttestationData`.
For that situation, `blst` started exposing Pippenger multiplication to accelerate this use case. Multiscalar multiplication is much faster than individual scalar multiplication of each signature / pubkey.
Further optimizations may be achieved with parallel tiling, see the Rust binding code in the `npoints >= 32` situation:
- https://github.com/supranational/blst/blob/v0.3.13/bindings/rust/src/pippenger.rs
Likewise, multiple pubkeys / signatures may be loaded simultaneously using the new `blst` APIs.
We don't do either of these additional optimizations as our architecture does not readily support them. Pippenger multiplication alone already offers a …
=> Expose Pippenger multiplication for combining multiple sigs of same msg

blscurve/blst/blst_aux_abi.nim
The functions in `blst_aux_abi.nim` require `blst_aux.h` not `blst.h`.
=> Use correct header file for `blst_aux` ABI
